### ISSUE TITLE
Deploy "customized" ISPmail /w Nginx, acme.sh - please advise

### ISSUE THREAD

**Issue by cmonty14** [Signum/ispmail-bookworm-ansible#8]
Hi,
I like ISPmail, and I prefer deployment using ansible.
However I prefer to use [(Free)Nginx](https://freenginx.org/) (as replacement for Apache) and [acme.sh](https://github.com/acmesh-official/acme.sh) (as replacement for certbot).

Could you please advise how to modify ansible?

THX

**Comment by Signum** [comment]
@cmonty14 I understand your preference for Nginx. But at the moment I cannot provide anything ready-to-use.

There are semi-official Ansible roles in the Ansible Galaxy for Nginx virtual hosts that you can use. Remember to also set up PHP. Same goes for acme.sh.

If you are not that familiar with Ansible: it's a useful asset and really not that hard to learn.
